export default mealsListMock = [
  {
    id: 1,
    mealName: 'Pohovana snicla',
    mealDescription: 'Zanimljiva snicla od mesa',
    pickUpStartTime: 18,
    pickUpEndTime: 23,
    donorAddress: 'Bul patrijarha Pavla 25, (sprat 3, stan 21)',
    donorPhone: '063198231',
  },
  {
    id: 2,
    mealName: 'Pohovana veverica',
    mealDescription: 'Zanimljiva snicla od veverice',
    pickUpStartTime: 10,
    pickUpEndTime: 13,
    donorAddress: 'Bul evrope 25',
    donorPhone: '063121231',
  },
  {
    id: 3,
    mealName: 'Pohovana piletina',
    mealDescription: 'Zanimljiva piletina od mesa',
    pickUpStartTime: 9,
    pickUpEndTime: 11,
    donorAddress: 'Karadjordjeva',
    donorPhone: '063198231',
  },
  {
    id: 4,
    mealName: 'Pohovana pacetina',
    mealDescription: 'Zanimljiva pacetina od mesa',
    pickUpStartTime: 8,
    pickUpEndTime: 23,
    donorAddress: 'Alekse santica 11',
    donorPhone: '0912039193',
  },
];
