version: "3.4"

services:
  web:
    image: codeforacause/podeli-obrok:#{TAG_NUMBER}#
    container_name: podeli-obrok-api
    ports:
      - "21000:3000"
    environment:
      DATABASE: "share-meal"
      DATABASE_USERNAME: "postgres"
      DATABASE_PASSWORD: "postgres"
      DATABASE_HOST: "db"
      APP_PORT: "3000"
      APP_NAME: "share-meal"

  db:
    image: postgres:13.5-alpine
    container_name: podeli-obrok-db
    ports:
      - 5432
    environment:
      POSTGRES_DB: "share-meal"
      POSTGRESS_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ".:/app:rw"
