version: "3.4"

services:
  web:
    build: .
    depends_on:
      - db
      - osm-search
    container_name: podeli-obrok-api
    ports:
      - "21000:3000"
    environment:
      DATABASE: "share-meal"
      DATABASE_USERNAME: "postgres"
      DATABASE_PASSWORD: "postgres"
      DATABASE_HOST: "db"
      APP_PORT: "3000"
      APP_NAME: "share-meal"
      OSM_SEARCH_API: "osm-search"
    restart: always

  osm-search:
    image: mediagis/nominatim:4.1
    container_name: osm-search-api
    depends_on:
      - db-nominatim
    environment:
      PBF_URL: "https://download.geofabrik.de/europe/serbia-latest.osm.pbf"
      REPLICATION_URL: "https://download.geofabrik.de/europe/serbia-updates"
      NOMINATIM_DATABASE_DSN: "pgsql:dbname=nominatim:15432;hostaddr=db-nominatim;user=postgres;password=postgres"
  db:
    image: postgres:13.5-alpine
    container_name: podeli-obrok-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "share-meal"
      POSTGRESS_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ".:/app:rw"
    restart: always
  db-nominatim:
    image: postgres:13.5-alpine
    container_name: nominatim-db
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: "nominatim"
      POSTGRESS_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    restart: always
